### ISSUE TITLE
Fix background issues in dashboard and sign in page

### ISSUE THREAD

**Issue by mahesh-krishnakumar** [mahesh-krishnakumar/wcpredictionapp#7]

**Comment by mahesh-krishnakumar** [comment]
Temporarily removed dashboard background: 8a716e6
Background updated for login page:  a4b4b40

**Comment by mahesh-krishnakumar** [comment]
Need to change navbar image in the dashboard to a higher resolution one.

**Comment by ajaleelp** [comment]
Not relevant anymore.
